FROM python:3.8.15
COPY main.py run.sh requirements.txt ./online_inference/

WORKDIR /online_inference

RUN python3 -m pip install --upgrade pip
RUN pip3 install -r requirements.txt

EXPOSE 8000

CMD ["bash", "run.sh"]