FROM python:3.8.15-slim-buster
COPY app_execution.sh tests_execution.sh requirements.txt ./online_inference/
COPY ./app ./online_inference/app

WORKDIR /online_inference

RUN python3 -m pip install --upgrade pip \
    && pip3 install -r requirements.txt

EXPOSE 8000

CMD ["bash", "app_execution.sh"]